Update 8 packages
gnupg (2.2.41-1 -> 2.2.42-1)
libfido2 (1.13.0-2 -> 1.14.0-1)
mingw-w64-i686-gettext (0.21.1-2 -> 0.22.4-3)
mingw-w64-i686-xxhash (0.8.2-1 -> 0.8.2-2)
mingw-w64-x86_64-gettext (0.21.1-2 -> 0.22.4-3)
mingw-w64-x86_64-xxhash (0.8.2-1 -> 0.8.2-2)
msys2-runtime (3.4.9-2 -> 3.4.10-1)
msys2-runtime-devel (3.4.9-2 -> 3.4.10-1)

Signed-off-by: Git for Windows Build Agent <ci@git-for-windows.build>

diff --git a/mingw64/share/doc/gettext/examples/build-aux/javaexec.sh.in b/mingw64/share/doc/gettext/examples/build-aux/javaexec.sh.in
--- a/mingw64/share/doc/gettext/examples/build-aux/javaexec.sh.in
+++ b/mingw64/share/doc/gettext/examples/build-aux/javaexec.sh.in
@@ -1,12 +1,12 @@
 #!/bin/sh
 # Execute a Java program.
 
-# Copyright (C) 2001-2022 Free Software Foundation, Inc.
+# Copyright (C) 2001-2023 Free Software Foundation, Inc.
 # Written by Bruno Haible <haible@clisp.cons.org>, 2001.
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 3 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
@@ -41,30 +41,18 @@ if test -n "@HAVE_JAVA_ENVVAR@"; then
 else
   unset JAVA_HOME
   export CLASSPATH
-  if test -n "@HAVE_GIJ@"; then
-    # In this case, $CONF_JAVA is "gij".
+  if test -n "@HAVE_JAVA@"; then
+    # In this case, $CONF_JAVA is "java".
     test -z "$JAVA_VERBOSE" || echo "$CONF_JAVA $@"
     exec $CONF_JAVA "$@"
   else
-    if test -n "@HAVE_JAVA@"; then
-      # In this case, $CONF_JAVA is "java".
+    if test -n "@HAVE_JRE@"; then
+      # In this case, $CONF_JAVA is "jre".
       test -z "$JAVA_VERBOSE" || echo "$CONF_JAVA $@"
       exec $CONF_JAVA "$@"
     else
-      if test -n "@HAVE_JRE@"; then
-        # In this case, $CONF_JAVA is "jre".
-        test -z "$JAVA_VERBOSE" || echo "$CONF_JAVA $@"
-        exec $CONF_JAVA "$@"
-      else
-        if test -n "@HAVE_JVIEW@"; then
-          # In this case, $CONF_JAVA is "jview".
-          test -z "$JAVA_VERBOSE" || echo "$CONF_JAVA $@"
-          exec $CONF_JAVA "$@"
-        else
-          echo 'Java virtual machine not found, try installing gij or set $JAVA, then reconfigure' 1>&2
-          exit 1
-        fi
-      fi
+      echo 'Java virtual machine not found, try setting $JAVA, then reconfigure' 1>&2
+      exit 1
     fi
   fi
 fi
