Update 4 packages
autoconf-wrapper (15-1 -> 20221207-1)
automake-wrapper (11-4 -> 20221207-1)
mingw-w64-i686-binutils (2.39-2 -> 2.39-3)
mingw-w64-x86_64-binutils (2.39-2 -> 2.39-3)

Signed-off-by: Git for Windows Build Agent <ci@git-for-windows.build>

diff --git a/usr/bin/autom4te b/usr/bin/autom4te
--- a/usr/bin/autom4te
+++ b/usr/bin/autom4te
@@ -1,6 +1,8 @@
 #!/bin/sh
-# Copyright 1999-2021 Gentoo Authors
+# Copyright 1999-2022 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
+
+NAME="autoconf"
 
 # Based on the ac-wrapper.pl script provided by MandrakeSoft
 # Rewritten in bash by Gregorio Guidi
@@ -15,8 +17,11 @@
 #     -or-
 #   - `configure' is already present and was generated by autoconf 2.13
 
-warn() { printf "ac-wrapper: $*\n" 1>&2; }
-err() { warn "$@"; exit 1; }
+(set -o posix) 2>/dev/null && set -o posix
+
+_stderr() { printf 'ac-wrapper: %s: %b\n' "${argv0}" "$*" 1>&2; }
+warn() { _stderr "warning: $*"; }
+err() { _stderr "error: $*"; exit 1; }
 unset IFS
 which() {
 	local p
@@ -33,7 +38,7 @@ which() {
 # Sanitize argv[0] since it isn't always a full path #385201
 #
 argv0=${0##*/}
-case ${0} in
+case $0 in
 	${argv0})
 		# find it in PATH
 		if ! full_argv0=$(which "${argv0}") ; then
@@ -45,10 +50,6 @@ case ${0} in
 		full_argv0=$0
 		;;
 esac
-
-if [ "${argv0}" = "ac-wrapper.sh" ] ; then
-	err "Don't call this script directly"
-fi
 
 if [ "${WANT_AUTOCONF}" = "2.1" ] && [ "${argv0}" = "autom4te" ] ; then
 	err "Autoconf 2.13 doesn't contain autom4te.\n" \
@@ -76,59 +77,68 @@ fi
 
 #
 # Set up bindings between actual version and WANT_AUTOCONF;
-# Start at last known unstable/stable versions to speed up lookup process.
+# Start with last known versions to speed up lookup process.
 #
-if [ -z "${KNOWN_AUTOCONF}" ] ; then
-	KNOWN_AUTOCONF="2.71:2.5 2.70:2.5 2.69:2.5"
-fi
-vers="${KNOWN_AUTOCONF} 9999:2.5 $(printf '2.%s:2.5 ' `seq 99 -1 59`) 2.13:2.1"
+LAST_KNOWN_VER="71"
+vers="9999"
+vers="${vers} $(printf '2.%s ' `seq ${LAST_KNOWN_VER} -1 50`)"
 
-binary=""
-for v in ${vers} ; do
-	auto_ver=${v%:*}
-	if [ -z "${binary}" ] && [ -x "${full_argv0}-${auto_ver}" ] ; then
-		binary="${full_argv0}-${auto_ver}"
-		break
-	fi
-done
-if [ -z "${binary}" ] ; then
-	err "Unable to locate any usuable version of autoconf.\n" \
-	    "\tI tried these versions: ${vers}\n" \
-	    "\tWith a base name of '${full_argv0}'."
-fi
+#
+# Helper to scan for a usable program based on version.
+#
+binary=
+all_vers=
+find_binary() {
+	local v
+	all_vers="${all_vers} $*" # For error messages.
+	for v ; do
+		if [ "${v}" = "2.1" ] ; then
+			v="2.13"
+		fi
+		if [ -x "${full_argv0}-${v}" ] ; then
+			binary="${full_argv0}-${v}"
+			binary_ver=${v}
+			return 0
+		fi
+	done
+	return 1
+}
 
 #
 # Check the WANT_AUTOCONF setting.  We accept a whitespace delimited
 # list of autoconf versions.
 #
-if [ -n "${WANT_AUTOCONF}" ] ; then
-	for v in ${vers} x ; do
-		if [ "${v}" = "x" ] ; then
-			warn "warning: invalid WANT_AUTOCONF '${WANT_AUTOCONF}'; ignoring."
-			unset WANT_AUTOCONF
-			break
-		fi
+find_latest() {
+	if ! find_binary ${vers} ; then
+		# Brute force it.
+		find_binary $(printf '2.%s ' `seq 99 -1 ${LAST_KNOWN_VER}`) 9999
+	fi
+}
+for wx in ${WANT_AUTOCONF:-latest} ; do
+	if [ "${wx}" = "latest" ] || [ "${wx}" = "2.5" ] ; then
+		find_latest && break
+	else
+		find_binary ${wx} && break
+	fi
+done
 
-		auto_ver=${v%:*}
-		want_ver=${v#*:}
-		for wx in ${WANT_AUTOCONF} ; do
-			if [ -x "${full_argv0}-${wx}" ] ; then
-				binary="${full_argv0}-${wx}"
-				v="x"
-			elif [ "${wx}" = "${want_ver}" ] && [ -x "${full_argv0}-${auto_ver}" ] ; then
-				binary="${full_argv0}-${auto_ver}"
-				v="x"
-			fi
-		done
-		[ "${v}" = "x" ] && break
-	done
+if [ -z "${binary}" ] && [ -n "${WANT_AUTOCONF}" ] ; then
+	warn "could not locate installed version for WANT_AUTOCONF='${WANT_AUTOCONF}'; ignoring"
+	unset WANT_AUTOCONF
+	find_latest
+fi
+
+if [ -z "${binary}" ] ; then
+	err "Unable to locate any usuable version of ${NAME}.\n" \
+	    "\tI tried these versions:${all_vers}\n" \
+	    "\tWith a base name of '${full_argv0}'."
 fi
 
 #
 # autodetect helpers
 #
 acprereq_version() {
-	sed -n -r \
+	sed -n -E \
 		-e '/^\s*(#|dnl)/d' \
 		-e '/AC_PREREQ/s:.*AC_PREREQ\s*\(\[?\s*([0-9.]+)\s*\]?\):\1:p' \
 		"$@" |
@@ -137,19 +147,41 @@ acprereq_version() {
 }
 
 generated_version() {
-	local re='^# Generated (by (GNU )?Autoconf|automatically using autoconf version) ([0-9.]+).*'
-	sed -n -r "/${re}/{s:${re}:\3:;p;q}" "$@"
+	local re='^# Generated (by (GNU )?Autoconf|automatically using autoconf version) (([0-9]+.)+[0-9]+).*$'
+	sed -n -E "/${re}/{s:${re}:\3:;p;q}" "$@"
+}
+
+recorded_aclocal_version() {
+	local re='.*m4_warning.*this file was generated for autoconf ([0-9].+)\..*'
+	sed -n -E "/${re}/{s:${re}:\1:;p;q}" "$@"
 }
 
 #
 # autodetect routine
 #
-if [ "${WANT_AUTOCONF}" = "2.1" ] && [ -f "configure.ac" ] ; then
-	err "Since configure.ac is present, aclocal always use\n" \
-	    "\tautoconf 2.59+, which conflicts with your choice and\n" \
-	    "\tcauses error. You have two options:\n" \
-	    "\t1. Try execute command again after removing configure.ac\n" \
-	    "\t2. Don't set WANT_AUTOCONF"
+if [ -z "${WANT_AUTOCONF}" ] ; then
+	auto_vers=
+	if [ -r "configure" ] ; then
+		auto_vers="${auto_vers} $(generated_version configure)"
+	fi
+	if [ -r "aclocal.m4" ] ; then
+		auto_vers="${auto_vers} $(recorded_aclocal_version aclocal.m4)"
+	fi
+	# We don't need to set $binary here as it has already been setup for us
+	# earlier to the latest available version.
+	if [ -n "${auto_vers}" ] ; then
+		if ! find_binary ${auto_vers} ; then
+			warn "auto-detected versions not found (${auto_vers}); falling back to latest available"
+		fi
+	fi
+fi
+
+if [ "${WANT_AUTOCONF}" = "2.1" -o "${WANT_AUTOCONF}" = "2.13" ] && [ -f "configure.ac" ] ; then
+	err \
+		"Since configure.ac is present, aclocal will always use autoconf 2.59+\n" \
+		"\twhich conflicts with your choice and causes errors. You have two options:\n" \
+		"\t1. Try executing the command again after removing configure.ac\n" \
+		"\t2. Don't set WANT_AUTOCONF (currently set to '${WANT_AUTOCONF}')"
 fi
 
 if [ "${WANT_AUTOCONF:-2.1}" = "2.1" ] && [ -n "${WANT_AUTOMAKE}" ] ; then
@@ -179,16 +211,7 @@ fi
 #
 # for further consistency
 #
-if [ -z "${WANT_AUTOCONF}" ] ; then
-	for v in ${vers} ; do
-		auto_ver=${v%:*}
-		want_ver=${v#*:}
-		if [ "${binary}" = "${full_argv0}-${auto_ver}" ] ; then
-			export WANT_AUTOCONF="${want_ver}"
-			break
-		fi
-	done
-fi
+export WANT_AUTOCONF="${binary_ver}"
 
 #
 # Now try to run the binary
@@ -196,7 +219,7 @@ fi
 if [ ! -x "${binary}" ] ; then
 	# this shouldn't happen
 	err "${binary} is missing or not executable.\n" \
-	    "\tPlease try emerging the correct version of autoconf."
+	    "\tPlease try installing the correct version of ${NAME}."
 fi
 
 exec "${binary}" "$@"
