Update 3 packages
mingw-w64-i686-c-ares (1.24.0-1 -> 1.25.0-1)
mingw-w64-x86_64-c-ares (1.24.0-1 -> 1.25.0-1)
pacman-contrib (1.9.1-1 -> 1.10.1-1)

Signed-off-by: Git for Windows Build Agent <ci@git-for-windows.build>

diff --git a/usr/bin/checkupdates b/usr/bin/checkupdates
--- a/usr/bin/checkupdates
+++ b/usr/bin/checkupdates
@@ -19,7 +19,7 @@
 #
 
 declare -r myname='checkupdates'
-declare -r myver='1.9.1'
+declare -r myver='1.10.1'
 
 LIBRARY=${LIBRARY:-'/usr/share/makepkg'}
 
@@ -27,7 +27,9 @@ DOWNLOAD_CACHE=0
 USE_COLOR='y'
 
 # Import libmakepkg
+# shellcheck source=/dev/null
 source "$LIBRARY"/util/message.sh
+# shellcheck source=/dev/null
 source "$LIBRARY"/util/parseopts.sh
 
 die() {
@@ -60,13 +62,17 @@ Options:
   -d, --download  download pending updates to the pacman cache
       --nocolor   do not colorize output
   -n, --nosync    do not sync the temporary database
+  -c, --change    print only when available updates differ from the last --change run
   -h, --help      display this help message and exit
   -V, --version   display version information and exit
 
 Environment Variables:
-  CHECKUPDATES_DB  override the path of the temporary database
-                   (default: "\${TMPDIR:-/tmp}/checkup-db-\${UID}")
-  TMPDIR           override the temporary directory (default: '/tmp')
+  CHECKUPDATES_DB      override the path of the temporary database
+                       (default: "\${TMPDIR:-/tmp}/checkup-db-\${UID}")
+  CHECKUPDATES_CHANGE  override the path of the temporary files for the "change" option
+                       (default: "\${XDG_STATE_HOME:-\$HOME/.local/state}/${myname}")
+  TMPDIR               override the temporary directory (default: '/tmp')
+  XDG_STATE_HOME       override the state directory (default: '\$HOME/.local/state')
 EOF
 }
 
@@ -74,8 +80,8 @@ version() {
 	printf "%s %s\n" "$myname" "$myver"
 }
 
-OPT_SHORT='dnhV'
-OPT_LONG=('download' 'nosync' 'help' 'nocolor' 'version')
+OPT_SHORT='dnchV'
+OPT_LONG=('download' 'nocolor' 'nosync' 'change' 'help' 'version')
 
 if ! parseopts "$OPT_SHORT" "${OPT_LONG[@]}" -- "$@"; then
 	exit 1
@@ -92,6 +98,8 @@ while :; do
 			USE_COLOR='n';;
 		-n|--nosync)
 			SYNC=0 ;;
+		-c|--change)
+			CHANGE=1 ;;
 		-h|--help)
 			usage
 			exit 0 ;;
@@ -118,25 +126,44 @@ fi
 
 trap 'rm -f $CHECKUPDATES_DB/db.lck' INT TERM EXIT
 
+if [[ -z $CHECKUPDATES_CHANGE ]]; then
+	CHECKUPDATES_CHANGE="${XDG_STATE_HOME:-$HOME/.local/state}/${myname}/"
+fi
+
 DBPath="$(pacman-conf DBPath)"
 if [[ -z "$DBPath" ]] || [[ ! -d "$DBPath" ]]; then
 	DBPath="/var/lib/pacman/"
 fi
 
-if (( ${SYNC} )); then
+if (( SYNC )); then
 	mkdir -p "$CHECKUPDATES_DB"
 	ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &> /dev/null
 	if ! pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
-	    die 'Cannot fetch updates'
+		die 'Cannot fetch updates'
 	fi
 fi
 mapfile -t updates < <(pacman -Qu --dbpath "$CHECKUPDATES_DB" 2> /dev/null | grep -v '\[.*\]')
 
 if (( ${#updates[@]} )); then
-	printf '%s\n' "${updates[@]}"
-	if (( DOWNLOAD_CACHE )); then
-		runcmd pacman -Sw --noconfirm "${updates[@]%% *}" --dbpath "$CHECKUPDATES_DB" --logfile /dev/null
+	if (( CHANGE )); then
+		mkdir -p "$CHECKUPDATES_CHANGE"
+		printf '%s\n' "${updates[@]}" > "$CHECKUPDATES_CHANGE/current_check"
+
+		if ! diff "$CHECKUPDATES_CHANGE/current_check" "$CHECKUPDATES_CHANGE/last_check" &>/dev/null; then
+			cat "$CHECKUPDATES_CHANGE/current_check"
+		fi
+
+		mv -f "$CHECKUPDATES_CHANGE/current_check" "$CHECKUPDATES_CHANGE/last_check"
+	else
+		printf '%s\n' "${updates[@]}"
+		if (( DOWNLOAD_CACHE )); then
+			runcmd pacman -Sw --noconfirm "${updates[@]%% *}" --dbpath "$CHECKUPDATES_DB" --logfile /dev/null
+		fi
 	fi
 else
+	if (( CHANGE )); then
+		mkdir -p "$CHECKUPDATES_CHANGE"
+		true > "$CHECKUPDATES_CHANGE/last_check"
+	fi
 	exit 2
 fi
diff --git a/usr/bin/pacscripts b/usr/bin/pacscripts
--- a/usr/bin/pacscripts
+++ b/usr/bin/pacscripts
@@ -25,11 +25,11 @@ set -o nounset
 set -o errexit
 
 declare -r myname='pacscripts'
-declare -r myver='1.9.1'
+declare -r myver='1.10.1'
 
 error() {
 	local mesg=$1; shift
-	printf "==> $(/usr/bin/gettext "ERROR:") ${mesg}\n" "$@" >&2
+	printf "==> $(/usr/bin/gettext "ERROR:") %s\n ${mesg}" "$@" >&2
 }
 
 usage() {
@@ -69,14 +69,16 @@ spacman() {
 print_db() {
 	pkg=$(pacman -Q "$1")
 	pkg=${pkg/ /-}
-	if [ -f $pac_db/$pkg*/install ]; then
-		cat $pac_db/$pkg*/install
-		echo
-		return 0
-	else
-		error "Package $1 does not include any .INSTALL script"
-		return 1
-	fi
+	for file in "$pac_db"/"$pkg"*/install; do
+		if [ -f "$file" ]; then
+			cat "$pac_db/$pkg*/install"
+			echo
+			return 0
+		else
+			error "Package $1 does not include any .INSTALL script"
+			return 1
+		fi
+	done
 }
 
 print_pkg() {
@@ -98,18 +100,18 @@ print_scriptlet() {
 		print_db "$1"
 		return
 	fi
-	if ! pacman -Si $1 &>/dev/null; then
+	if ! pacman -Si "$1" &>/dev/null; then
 		error "Package $1 not found"
 		return 1
 	fi
-	url=$(pacman -Sddp $1)
+	url=$(pacman -Sddp "$1")
 	if [[ $url != file://* ]]; then
-		if ! spacman -Sddw --logfile /dev/null --noconfirm $1 >&2; then
+		if ! spacman -Sddw --logfile /dev/null --noconfirm "$1" >&2; then
 			error "Failed to download $1"
 			return 1
 		fi
 		echo >&2
-		url=$(pacman -Sddp $1)
+		url=$(pacman -Sddp "$1")
 	fi
 	print_pkg "${url#file://}"
 	return
@@ -123,5 +125,5 @@ fi
 case "$1" in
 	--help|-h) usage; exit 0 ;;
 	--version|-V) version; exit 0 ;;
-	*) print_scriptlet $1 ;;
+	*) print_scriptlet "$1" ;;
 esac
