Upgrade all packages
Most importantly libserf, which will hopefully address
https://github.com/git-for-windows/git/issues/1993...

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/usr/bin/git-flow-bugfix b/usr/bin/git-flow-bugfix
--- a/usr/bin/git-flow-bugfix
+++ b/usr/bin/git-flow-bugfix
@@ -11,7 +11,7 @@
 #    http://github.com/petervanderdoes/gitflow
 #
 # Authors:
-# Copyright 2012-2017 Peter van der Does. All rights reserved.
+# Copyright 2012-2019 Peter van der Does. All rights reserved.
 #
 # Original Author:
 # Copyright 2010 Vincent Driessen. All rights reserved.
@@ -199,7 +199,6 @@ F,[no]fetch      Fetch from origin before performing local operation
 
 	require_base_is_local_branch "$base"
 	gitflow_require_name_arg
-	gitflow_config_set_base_branch $base $BRANCH
 
 	# Update the local repo with remote changes, if asked
 	if flag fetch; then
@@ -217,6 +216,7 @@ F,[no]fetch      Fetch from origin before performing local operation
 
 	run_pre_hook "$NAME" "$ORIGIN" "$BRANCH" "$base"
 
+	gitflow_config_set_base_branch $base $BRANCH
 
 	# create branch
 	git_do checkout -b "$BRANCH" "$base" || die "Could not create bugfix branch '$BRANCH'."
@@ -438,6 +438,10 @@ helper_finish_cleanup() {
 	remotebranchdeleted=$FLAGS_FALSE
 	localbranchdeleted=$FLAGS_FALSE
 
+	if flag push; then
+		git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
+	fi
+
 	if noflag keep; then
 
 		# Always delete remote first
@@ -467,10 +471,6 @@ helper_finish_cleanup() {
 		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
 			gitflow_config_remove_base_section "$BRANCH"
 		fi
-	fi
-
-	if flag push; then
-		git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
 	fi
 
 	echo
@@ -598,7 +598,7 @@ showcommands!    Show git commands while executing them
 	base=$(gitflow_config_get_base_branch $BRANCH)
 	base=${base:-$DEVELOP_BRANCH}
 
-	git_do diff "$base..$BRANCH"
+	git_do diff "$base...$BRANCH"
 }
 
 cmd_checkout() {
diff --git a/usr/bin/git-flow-hotfix b/usr/bin/git-flow-hotfix
--- a/usr/bin/git-flow-hotfix
+++ b/usr/bin/git-flow-hotfix
@@ -11,7 +11,7 @@
 #    http://github.com/petervanderdoes/gitflow
 #
 # Authors:
-# Copyright 2012-2017 Peter van der Does. All rights reserved.
+# Copyright 2012-2019 Peter van der Does. All rights reserved.
 #
 # Original Author:
 # Copyright 2010 Vincent Driessen. All rights reserved.
@@ -189,7 +189,6 @@ F,[no]fetch       Fetch from origin before performing local operation
 	# No need to continue if not clean
 	require_base_is_local_branch "$base"
 	git_config_bool_exists "gitflow.allowdirty" || require_clean_working_tree
-	gitflow_config_set_base_branch $base $BRANCH
 
 	# Update the local repo with remote changes, if asked
 	if flag fetch; then
@@ -218,6 +217,8 @@ F,[no]fetch       Fetch from origin before performing local operation
 	fi
 
 	run_pre_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH" "$base"
+
+	gitflow_config_set_base_branch $base $BRANCH
 
 	# Create branch
 	git_do checkout -b "$BRANCH" "$base"  || die "Could not create hotfix branch '$BRANCH'."
@@ -581,6 +582,16 @@ T,tagname!            Use given tag name
 
 	run_post_hook "$VERSION_PREFIX$TAGNAME" "$ORIGIN" "$BRANCH"
 
+	if flag push; then
+		if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
+			git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
+		fi
+		git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
+		if noflag notag; then
+			git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
+		fi
+	fi
+
 	# Delete branch
 	if noflag keep; then
 
@@ -608,16 +619,6 @@ T,tagname!            Use given tag name
 			gitflow_config_remove_base_section "$BRANCH"
 		fi
 
-	fi
-
-	if flag push; then
-		if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
-			git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
-		fi
-		git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
-		if noflag notag; then
-			git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
-		fi
 	fi
 
 	echo
