Update 76 packages
apr-util (1.6.3-2 -> 1.6.5-1)
bash (5.3.015-1 -> 5.3.015-2)
bsdcpio (3.8.8-1 -> 3.8.9-1)
bsdtar (3.8.8-1 -> 3.8.9-1)
ca-certificates (20250419-1 -> 20260816-1)
curl (8.21.0-1 -> 8.22.0-1)
dos2unix (7.5.6-1 -> 7.5.7-1)
expat (2.8.2-1 -> 2.8.4-1)
findutils (4.10.0-3 -> 4.11.0-2)
gnupg (2.4.9-1 -> 2.4.9-3)
isl (0.27-1 -> 0.28-1)
libarchive (3.8.8-1 -> 3.8.9-1)
libcurl (8.21.0-1 -> 8.22.0-1)
libexpat (2.8.2-1 -> 2.8.4-1)
libffi (3.7.1-1 -> 3.8.0-1)
libltdl (2.5.4-5 -> 2.6.2-1)
libnghttp2 (1.69.0-1 -> 1.70.0-1)
libp11-kit (0.26.4-1 -> 0.26.5-1)
libpcre2_16 (10.47-1 -> 10.48-1)
libpcre2_32 (10.47-1 -> 10.48-1)
libpcre2_8 (10.47-1 -> 10.48-1)
libpcre2posix (10.47-1 -> 10.48-1)
libpsl (0.21.5-2 -> 0.23.2-1)
libsqlite (3.53.3-1 -> 3.53.4-1)
libtool (2.5.4-5 -> 2.6.2-1)
lndir (1.0.5-1 -> 1.0.6-1)
mingw-w64-ucrt-x86_64 (7zip-26.02-1 -> 7zip-26.03-1)
mingw-w64-ucrt-x86_64-binutils (2.47-1 -> 2.47-3)
mingw-w64-ucrt-x86_64-bzip2 (1.0.8-3 -> 1.0.8-4)
mingw-w64-ucrt-x86_64-ca-certificates (20250419-1 -> 20260816-1)
mingw-w64-ucrt-x86_64-crt (14.0.0.r220.gd999af622-1 -> 14.0.0.r353.g6df76fa52-4)
mingw-w64-ucrt-x86_64-curl-openssl-alternate (8.21.0-2 -> 8.22.0-1)
mingw-w64-ucrt-x86_64-curl-winssl (8.21.0-2 -> 8.22.0-1)
mingw-w64-ucrt-x86_64-expat (2.8.2-1 -> 2.8.4-2)
mingw-w64-ucrt-x86_64-gcc (16.1.0-5 -> 16.2.0-3)
mingw-w64-ucrt-x86_64-gcc-libs (16.1.0-5 -> 16.2.0-3)
mingw-w64-ucrt-x86_64-git (2.55.0.2-1 -> 2.55.0.5-1)
mingw-w64-ucrt-x86_64-git-credential-wincred (2.55.0.2-1 -> 2.55.0.5-1)
mingw-w64-ucrt-x86_64-git-doc-html (2.55.0.2-1 -> 2.55.0.5-1)
mingw-w64-ucrt-x86_64-git-for-windows-addons (2.55.0.2-1 -> 2.55.0.5-1)
mingw-w64-ucrt-x86_64-git-gui (2.55.0.2-1 -> 2.55.0.5-1)
mingw-w64-ucrt-x86_64-git-lfs (3.7.1-1 -> 3.8.0-1)
mingw-w64-ucrt-x86_64-git-perl (2.55.0.2-1 -> 2.55.0.5-1)
mingw-w64-ucrt-x86_64-git-send-email (2.55.0.2-1 -> 2.55.0.5-1)
mingw-w64-ucrt-x86_64-git-subtree (2.55.0.2-1 -> 2.55.0.5-1)
mingw-w64-ucrt-x86_64-git-svn (2.55.0.2-1 -> 2.55.0.5-1)
mingw-w64-ucrt-x86_64-gitk (2.55.0.2-1 -> 2.55.0.5-1)
mingw-w64-ucrt-x86_64-headers (14.0.0.r220.gd999af622-1 -> 14.0.0.r353.g6df76fa52-2)
mingw-w64-ucrt-x86_64-libffi (3.7.1-1 -> 3.8.0-1)
mingw-w64-ucrt-x86_64-libmangle (14.0.0.r220.gd999af622-1 -> 14.0.0.r353.g6df76fa52-2)
mingw-w64-ucrt-x86_64-libsystre (1.0.2-2 -> 1.0.2-3)
mingw-w64-ucrt-x86_64-libwinpthread (14.0.0.r220.gd999af622-1 -> 14.0.0.r353.g6df76fa52-2)
mingw-w64-ucrt-x86_64-openssl (3.6.3-1 -> 3.6.4-1)
mingw-w64-ucrt-x86_64-osslsigncode (2.13-1 -> 2.14-1)
mingw-w64-ucrt-x86_64-p11-kit (0.26.4-1 -> 0.26.5-1)
mingw-w64-ucrt-x86_64-pcre2 (10.47-1 -> 10.48-3)
mingw-w64-ucrt-x86_64-pkgconf (1~3.0.4-1 -> 1~3.0.7-1)
mingw-w64-ucrt-x86_64-python (3.14.6-2 -> 3.14.7-1)
mingw-w64-ucrt-x86_64-tools (14.0.0.r220.gd999af622-1 -> 14.0.0.r353.g6df76fa52-2)
mingw-w64-ucrt-x86_64-windows-default-manifest (6.4-4 -> 20260815-1)
mingw-w64-ucrt-x86_64-winpthreads (14.0.0.r220.gd999af622-1 -> 14.0.0.r353.g6df76fa52-2)
msys2-keyring (1~20260214-1 -> 1~20260814-1)
nano (9.1-1 -> 9.2-1)
openssh (10.4p1-1 -> 10.5p1-1)
p11-kit (0.26.4-1 -> 0.26.5-1)
pacman-contrib (1.10.6-1 -> 1.10.6-2)
pcre2 (10.47-1 -> 10.48-1)
perl (5.42.2-1 -> 5.42.3-1)
perl-Authen-SASL (2.2000-1 -> 2.2100-1)
perl-LWP-MediaTypes (6.04-2 -> 6.05-1)
perl-MIME-tools (5.517-1 -> 5.518-1)
perl-URI (5.35-1 -> 5.37-1)
python (3.12.13-1 -> 3.12.14-1)
rsync (3.4.4-1 -> 3.5.0-1)
swig (4.4.0-1 -> 4.5.0-1)
vim (9.2.0858-1 -> 9.2.0858-3)

Signed-off-by: Git for Windows Build Agent <ci@git-for-windows.build>

diff --git a/usr/bin/updatedb b/usr/bin/updatedb
--- a/usr/bin/updatedb
+++ b/usr/bin/updatedb
@@ -1,6 +1,6 @@
 #! /bin/sh
 # updatedb -- build a locate pathname database
-# Copyright (C) 1994-2024 Free Software Foundation, Inc.
+# Copyright (C) 1994-2026 Free Software Foundation, Inc.
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -21,8 +21,8 @@
 #set -x
 
 version='
-updatedb (GNU findutils) 4.10.0
-Copyright (C) 1994-2024 Free Software Foundation, Inc.
+updatedb (GNU findutils) 4.11.0
+Copyright (C) 1994-2026 Free Software Foundation, Inc.
 License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
 This is free software: you are free to change and redistribute it.
 There is NO WARRANTY, to the extent permitted by law.
@@ -39,7 +39,7 @@ Written by Eric B. Decker, James Youngman, and Kevin Dalley.
 # character encoding errors in text-based tools like "sort".  To avoid
 # this, we set LC_ALL=C.  This will, presumably, not work perfectly on
 # systems where LC_ALL is not the way to do locale configuration or
-# some other seting can override this.
+# some other setting can override this.
 LC_ALL=C
 export LC_ALL
 
@@ -147,7 +147,7 @@ select_shell() {
 # Any global options for find?
 : ${FINDOPTIONS=}
 
-# What shell shoud we use?  We should use a POSIX-ish sh.
+# What shell should we use?  We should use a POSIX-ish sh.
 : ${SHELL="/bin/sh"}
 
 # Non-network directories to put in the database.
@@ -242,14 +242,14 @@ checkbinary () {
     if test -x "$1" ; then
 	: ok
     else
-      eval echo "updatedb needs to be able to execute $1, but cannot." >&2
+      echo "updatedb needs to be able to execute '$1', but cannot." >&2
       exit 1
     fi
 }
 
-for binary in $find $frcode
+for binary in "$find" "$frcode"
 do
-  checkbinary $binary
+  checkbinary "$binary"
 done
 
 
