install-pacman-packages: take care of very large DLLs
We need to install Rust in Git for Windows' SDK, but there's a snag:
`cargo.exe` depends on `libLLVM-22.dll` which currently weighs ~140MB.
We can commit that, but we cannot push it because GitHub has a hard
limit: (uncompressed) blob objects cannot be larger than 100MB.

We had a similar problem in git-sdk-arm64 because there, we don't use
GCC, but Clang. And Clang already depends on libLLVM.

The way we solved it there, at first, was to use `llvm-strip.exe` (see
https://github.com/git-for-windows/git-sdk-arm64/4e626dd04e3 (sync:
avoid running into GitHub's file size limits, 2023-04-25)) to reduce the
file size. Later on, we started building a substantially reduced libLLVM
in Git for Windows, using `-DCMAKE_BUILD_TYPE=MinSizeRel`, see
https://github.com/git-for-windows/MINGW-packages/pull/75.

My original desire was to use UPX, a packer that allows DLLs and EXEs to
be compressed such that they decompress on the fly upon being loaded.
That would have been my ideal solution, but back then there was no
Windows/ARM64 support in UPX.

However, we're talking about the x86_64 side of things, and it works
beautifully, shrinking libLLVM from ~140MB to ~45MB. So let's do that.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/.github/workflows/install-pacman-packages.yml b/.github/workflows/install-pacman-packages.yml
--- a/.github/workflows/install-pacman-packages.yml
+++ b/.github/workflows/install-pacman-packages.yml
@@ -63,6 +63,37 @@ jobs:
             esac
           done
           pacman -S --needed --noconfirm "${packages[@]}"
+      - name: deal with large DLL files
+        shell: bash
+        run: |
+          set -ex
+          large_dlls=$(find ucrt64/bin -size +100M)
+          test -n "$large_dlls" || exit 0
+
+          # Okay, we have a problem. GitHub does not like to host files >100MB.
+          # But libLLVM-<version>.dll easily blasts through that limit.
+          #
+          # But we're in luck, because upx exists (https://upx.github.io/), a
+          # fast packer for executables. As an example, it can compress
+          # libLLVM-22.dll from 147017728 -> 45706752. So let' use that for
+          # large DLLs and EXEs.
+
+          pacman -S --noconfirm mingw-w64-ucrt-x86_64-upx
+          ret=0
+          for dll in $large_dlls
+          do
+            /ucrt64/bin/upx.exe $dll || ret=1
+          done
+          test 0 = $ret || exit $ret
+
+          large_dlls=$(find ucrt64/bin -size +100M)
+          test -z "$large_dlls" || {
+            echo "::error::large file(s): $large_dlls" >&2
+            exit 1
+          }
+
+          # Clean up; We do *not* want UPX in the Git for Windows SDK...
+          pacman -R --unneeded --noconfirm mingw-w64-ucrt-x86_64-upx
       - name: Commit and push SDK
         shell: bash
         run: |
